# Generated by Django 3.2.18 on 2023-03-12 11:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=100)),
                ('number_of_employees', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('secondPhoneNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('about_compony', models.TextField(max_length=300)),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('salary', models.IntegerField(null=True)),
                ('specialist', models.CharField(choices=[('Backend-разработчик', 'Backend-разработчик'), ('Frontend-разработчик', 'Frontend-разработчик'), ('Data Science', 'Data Science')], default='Разработчик', max_length=40)),
            ],
        ),
    ]
