# Generated by Django 3.2.18 on 2023-03-13 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_employer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_compony', models.TextField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='employer',
            name='about_compony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.about', verbose_name='акансия'),
        ),
    ]
