# Generated by Django 3.2.18 on 2023-03-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_auto_20230313_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='specialist',
        ),
        migrations.AddField(
            model_name='about',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='specialist',
            field=models.CharField(choices=[('Backend-разработчик', 'Backend-разработчик'), ('Frontend-разработчик', 'Frontend-разработчик'), ('Data Science', 'Data Science')], default='Разработчик', max_length=40),
        ),
    ]
