# Generated by Django 3.2.18 on 2023-03-13 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_auto_20230313_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='about_compony',
        ),
        migrations.AddField(
            model_name='about',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enterprise.employer', verbose_name='Компания'),
            preserve_default=False,
        ),
    ]
